import Head from 'next/head';
import styles from '../styles/Home.module.css';
import NavBar from '../components/NavBar';
import CodeBlock from '../components/CodeBlock';

export default function Home() {
  return (
    <>
      <Head>
        <title>Jason D. Allen</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={styles.container}>
        <NavBar />
        <main className={styles.main}>
          <div className={styles.bio}>
            <CodeBlock />
            <div className={styles.contact}>
              <button className={styles.btn}>Get in touch.</button>
            </div>
          </div>
          <div className={styles.welcome}>
            <h2>&lt;coder&gt;</h2>
            <h1>
              Using elegant code to craft
              <span className='clean'>beautifully simple</span> web experiences.
            </h1>
            <h2>&lt;/coder&gt;</h2>
          </div>
        </main>
      </div>
    </>
  );
}
