import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import NavBar from '../components/NavBar';
import CodeBlock from '../components/CodeBlock';

export default function Home() {
  return (
    <>
      <Head>
        <title>Jason D. Allen</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={styles.container}>
        <NavBar />
        <main>
          <CodeBlock />
        </main>
      </div>
    </>
  );
}
